"""Change deleted to archived in Report model

Revision ID: 21d3b906189e
Revises: 989b28ed196a
Create Date: 2025-12-14 14:36:08.410466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d3b906189e'
down_revision = '989b28ed196a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new archived column with default 0
    op.add_column('reports', sa.Column('archived', sa.Integer(), nullable=True, server_default='0'))
    
    # Copy data from deleted to archived for existing records (SQLite compatible)
    op.execute("UPDATE reports SET archived = COALESCE(deleted, 0)")
    
    # Drop the old deleted column
    op.drop_column('reports', 'deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('deleted', sa.INTEGER(), nullable=True))
    op.drop_column('reports', 'archived')
    # ### end Alembic commands ###


