"""Change deleted to archived in Report model

Revision ID: 5453fbc7ccf0
Revises: 21d3b906189e
Create Date: 2025-12-14 18:02:41.319701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5453fbc7ccf0'
down_revision = '21d3b906189e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


