"""Initial schema

Revision ID: 989b28ed196a
Revises: 
Create Date: 2025-12-12 00:00:47.339271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989b28ed196a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('msg_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('ai_category', sa.String(length=50), nullable=False),
    sa.Column('action_taken', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_action_taken'), 'action_logs', ['action_taken'], unique=False)
    op.create_index(op.f('ix_action_logs_ai_category'), 'action_logs', ['ai_category'], unique=False)
    op.create_index(op.f('ix_action_logs_msg_id'), 'action_logs', ['msg_id'], unique=True)
    op.create_index(op.f('ix_action_logs_timestamp'), 'action_logs', ['timestamp'], unique=False)
    op.create_table('progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('total_processed', sa.Integer(), nullable=False),
    sa.Column('important', sa.Integer(), nullable=True),
    sa.Column('action_required', sa.Integer(), nullable=True),
    sa.Column('newsletter', sa.Integer(), nullable=True),
    sa.Column('social', sa.Integer(), nullable=True),
    sa.Column('review', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('progress')
    op.drop_index(op.f('ix_action_logs_timestamp'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_msg_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_ai_category'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_action_taken'), table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###

